import type { NextPage } from "next";
import Head from "next/head";

import { MainSection } from "../components/Sections/Main";
import { AuthSection } from "../components/Sections/Auth";
import { HealthcareSection } from "../components/Sections/Healthcare";
import { ContactSection } from "../components/Sections/Contact";

import { Container } from "../styles/pages/home";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GoCorona | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Container>
        <MainSection />
        <AuthSection />
        <ContactSection />
        <HealthcareSection />
      </Container>
    </div>
  );
};

export default Home;
