import type { NextPage } from "next";
import Head from "next/head";

import { MainSection } from "../screens/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GoCorona | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main>
        <MainSection />
      </main>
    </div>
  );
};

export default Home;
